# Generated by Django 4.0.1 on 2022-01-20 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_shop_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='filename',
            field=models.FileField(blank=True, null=True, upload_to='Shops', verbose_name='Файл с товарами магазина'),
        ),
    ]
