# Generated by Django 4.0.1 on 2022-01-21 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_shop_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='price_rrc',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='shop',
            name='filename',
            field=models.FileField(blank=True, null=True, upload_to='shops', verbose_name='Файл с товарами магазина'),
        ),
    ]
