# Generated by Django 4.0.1 on 2022-01-27 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_shop_owner_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='shop',
        ),
    ]
