# Generated by Django 4.0.1 on 2022-01-30 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_orderitem_shop'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='contact',
            constraint=models.UniqueConstraint(fields=('type', 'user_id'), name='Контакт уже создан'),
        ),
    ]
